version: 1
builder:
  configs:
    - documentation_targets:
        - SophonCore
        - SophonGemini
        - SophonOpenAI
        - SophonAnthropic
      platform: ios
      scheme: Sophon-Package
    - platform: macos-xcodebuild
      scheme: Sophon-Package
